repos:
- repo: local
  hooks:
    - id: go-fmt
      name: go fmt
      entry: go fmt ./...
      language: system
      types: [go]
      pass_filenames: false

    - id: go-vet
      name: go vet
      entry: go vet ./...
      language: system
      types: [go]
      pass_filenames: false

    - id: go-lint
      name: golangci-lint
      entry: golangci-lint run
      language: system
      types: [go]
      pass_filenames: false

    - id: go-test
      name: go test
      entry: go test ./...
      language: system
      types: [go]
      pass_filenames: false

    - id: go-mod-tidy
      name: go mod tidy
      entry: go mod tidy
      language: system
      pass_filenames: false
      files: go.mod|go.sum

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
